(() => {
  const A = window.__TB;
  const tr = (hi,en) => A.L({hi,en});
  const sources = [
    ['HRA','Y 20% · Z 10% · 01-11-2024','https://finance.rajasthan.gov.in/PDFDOCS/RULES/14114.pdf'],
    ['DA','60% · 01-01-2026','https://finance.rajasthan.gov.in/PDFDOCS/RULES/14945.pdf'],
    ['SI','₹800 / 1,200 / 2,200 / 3,000 / 5,000','https://sipf.rajasthan.gov.in/SIPremiumRates.aspx'],
    ['RGHS','₹265 / 440 / 658 / 875 · 01-04-2022','https://rghs.rajasthan.gov.in/Circular_10.pdf'],
    ['GPF','SIPF subscription slabs · March 2018','https://sipf.rajasthan.gov.in/GPFSubscriptionSlabs.aspx'],
    ['PM POSHAN','₹6.78 / ₹10.17 · 01-05-2025','https://pmposhan.education.gov.in/Meal%20Provision.html'],
  ];
  const strip = () => `<div class="source-strip"><span>${tr('स्रोत जाँच: 5 सितम्बर 2026 · जानकारी अपने-आप अपडेट नहीं होती।','Sources reviewed: 5 September 2026 · Information does not update automatically.')}</span><a href="#/verification">${tr('स्रोत और बाकी सुविधाएँ देखें','View sources and remaining features')}</a></div>`;
  A.NAV[A.NAV.length-1].items.push({id:'verification',icon:'check',t:{hi:'स्रोत और सुविधा जाँच',en:'Sources & feature review'}});
  window.PAGES.verification = () => `<div class="tb-work">${A.pageHead(tr('राजस्थान · समीक्षा','Rajasthan · review'),tr('स्रोत और सुविधा जाँच','Sources & feature review'),tr('जाँच की तारीख: 5 सितम्बर 2026','Review date: 5 September 2026'))}
    <section class="panel"><h2>${tr('किन दरों के स्रोत जाँचे गए?','Which rate sources were checked?')}</h2><p>${tr('नीचे दिए स्रोतों से डिफ़ॉल्ट दरें मिलाई गई हैं। प्रभावी तारीख हर पंक्ति में है। बाद के आदेश और आपके वेतन बिल की वास्तविक कटौती लागू हो सकती है; कैलकुलेटर में वास्तविक कटौती भर सकते हैं।','Default rates were checked against the sources below. Effective dates are shown where available. Later orders and your actual payroll deductions may apply; actual deductions can be entered in the calculator.')}</p>${sources.map(s=>`<div class="source-strip"><strong>${s[0]}</strong><span>${s[1]}</span><a href="${s[2]}" target="_blank" rel="noopener noreferrer">${tr('आधिकारिक स्रोत ↗','Official source ↗')}</a></div>`).join('')}</section>
    <section class="panel"><h2>${tr('ताज़ा आदेश और पुष्टि बाकी','Recent orders and checks still pending')}</h2><p>${tr('वित्त विभाग की सूची में 3 सितम्बर 2026 का RSR संशोधन उपलब्ध है। लागू शर्तें मूल आदेश में देखें। शिविरा 2026–27 की सभी तिथियाँ, प्रशिक्षण समय-सीमाएँ और हर पुराने लिंक की पूर्ण पुष्टि बाकी है। आयकर टूल सीमित अनुमान है; चालू कर वर्ष के अंतिम नियम की पुष्टि करें।','The Finance Department lists an RSR amendment dated 3 September 2026. Read the original order for its conditions. All Shivira 2026–27 dates, training deadlines and every legacy link have not been fully verified. The tax tool is a limited estimate; confirm final rules for the current tax year.')}</p><p><a href="https://finance.rajasthan.gov.in/website/Default.aspx" target="_blank" rel="noopener noreferrer">${tr('वित्त विभाग के आदेश ↗','Finance Department orders ↗')}</a> · <a href="https://rajshaladarpan.rajasthan.gov.in/" target="_blank" rel="noopener noreferrer">Shala Darpan ↗</a> · <a href="https://www.incometax.gov.in/iec/foportal/" target="_blank" rel="noopener noreferrer">Income Tax ↗</a></p></section>
    <section class="panel"><h2>${tr('CCE Guru APK: क्या शामिल है?','CCE Guru APK: what is included?')}</h2><p>${tr('74 HTML फ़ाइलों और 52 activity नामों की स्थिर जाँच हुई; APK चलाकर हर स्क्रीन की जाँच नहीं हुई। विद्यार्थी, पोर्टफोलियो, आकलन, समय-सारणी, भोजन लेखा, रजिस्टर और आवेदन के स्वतंत्र ऑफ़लाइन विकल्प उपलब्ध हैं।','Static inspection covered 74 HTML files and 52 activity names; the APK was not executed to test every screen. Independent offline alternatives cover students, portfolios, assessments, timetables, meal accounting, registers and application drafts.')}</p><h3>${tr('अभी बाकी / आंशिक','Still missing / partial')}</h3><ul><li>${tr('जिला-विशिष्ट प्रमाणित UC/MDCF और हूबहू सरकारी पोर्टफोलियो प्रारूप।','District-specific certified UC/MDCF and exact government portfolio layouts.')}</li><li>${tr('पूरा आधिकारिक baseline/SA प्रश्न बैंक और निर्धारित प्रखर समय-सारणी।','Complete official baseline/SA question banks and prescribed Prakhar schedules.')}</li><li>${tr('Sudoku; सरकारी पोर्टल लॉगिन/जमा करना ऑनलाइन ही है।','Sudoku; government portal login and submission remain online.')}</li><li>${tr('बाहरी PDF ऑफ़लाइन संग्रह और पुराने टूल का एकीकृत बैकअप।','Offline external PDFs and unified backup of legacy tools.')}</li></ul><p>${tr('इसलिए पूर्ण APK समानता या हर जानकारी के नवीनतम होने का दावा नहीं किया गया है।','Complete APK parity and universal freshness are not claimed.')}</p></section></div>`;
  for (const id of ['home','salary','shivira','training','orders','resources','tools']) {
    const original = window.PAGES[id];
    if(original) window.PAGES[id] = (...args) => strip()+original(...args);
  }
})();
